# Generated by Django 5.2.6 on 2025-09-30 15:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='core.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='products', to='core.category'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='old_category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='old_product', to='core.category'),
            preserve_default=False,
        ),
    ]
