# Generated by Django 5.2.7 on 2025-10-07 15:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(upload_to=account.models._get_avatar_upload_path),
        ),
    ]
